FelipeSiravegna/ProyectoGrupal-Backend

api/index.js

add index config

---

api/src/models/Genre.js

add genre model

---

api/src/models/Movie.js

add: movie models

---

api/src/controllers/GET/Image/index.js
api/src/controllers/GET/MovieDetail/index.js
api/src/controllers/GET/Video/index.js
api/src/db.js
api/src/routes/GET/MovieDetail/index.js
api/src/routes/index.js

-Image and Video controllers working
-MovieDetail controller getMovieFromDB function error: "Cannot read properties of undefined (reading 'findOne')"
-db.js now has Movie model
-routes/GET/MovieDetail/index.js route added
-routes/index.js detail route added

Get detail route+get image route+get video route

---

api/src/controllers/GET/users/index.js
api/src/controllers/POST/user
api/src/controllers/PUT/user/index.js
api/src/models/User.js
api/src/routes/GET/users/user
api/src/routes/PUT/user/index.js

Fix user model, create user routes (POST, PUT, GET)

User Route

---

api/src/controllers/GET/users/index.js
api/src/controllers/POST/user
api/src/controllers/PUT/user/index.js
api/src/routes/DELETE/user/index.js
api/src/routes/GET/users/bannedUsers.js
api/src/routes/GET/users/user
api/src/routes/GET/users/users
api/src/routes/POST/user/index.js
api/src/routes/PUT/user/admin.js
api/src/routes/PUT/user/index.js
api/src/routes/PUT/user/public.js
api/src/routes/index.js

CHANGED FILES:
.......................routes.......................
api\src\routes\index.js
api\src\routes\GET\users\index.js
api\src\routes\GET\users\user.js
api\src\routes\POST\user\index.js
.......................controllers.......................
api\src\controllers\GET\users\index.js
api\src\controllers\POST\user\index.js
CREATED FILES:
.......................routes.......................
api\src\routes\GET\users\bannedUsers.js
api\src\routes\PUT\user\index.js
api\src\routes\PUT\user\public.js
api\src\routes\PUT\user\admin.js
api\src\routes\DELETE\user\index.js
.......................controllers.......................
api\src\controllers\PUT\user\index.js

User routes

---

api/src/controllers/GET/Credits/index.js
api/src/controllers/GET/CreditsFromAPI/index.js
api/src/controllers/GET/MovieDetail/index.js
api/src/controllers/GET/MovieDetailFromAPI/index.js
api/src/controllers/GET/MovieDetailFromDB/index.js
api/src/controllers/GET/NowPlaying/index.js
api/src/controllers/GET/TrailerFromAPI/index.js
api/src/routes/GET/ComingSoon/index.js
api/src/routes/GET/MovieDetail/index.js
api/src/routes/GET/NowPlaying/index.js
api/src/routes/index.js

-nowPlaying route added 
-movieDetailFromApi added in case someone wants to see the detail of a nowPlayingMovie that is not in the db

Now playing route

---

api/src/controllers/PUT/user/index.js

Tenía los controllers de GET/users erroneamente.

Fix update user controllers.

---

api/index.js
api/src/controllers/GET/MovieDetailFromDB/index.js
api/src/controllers/GET/movies/popular.js
api/src/controllers/GET/movies/search.js
api/src/db.js
api/src/models/Movie.js
api/src/routes/POST/Movie/index.js

-Cambios en las relaciones USER-LIST, DIRECTOR-MOVIE
-El modelo MOVIES ahora se llama MOVIE
-Tablas intermedias se cargan al levantar el servidor

relation fixes

---

api/src/controllers/GET/movies/filters/actionFilter.js
api/src/controllers/GET/movies/filters/directorsFilter.js
api/src/controllers/GET/movies/filters/genresFilter.js
api/src/controllers/GET/movies/search.js
api/src/routes/GET/movies/search.js

no es mucho pero es trabajo honesto

Search route+filters aplied

---

api/src/controllers/GET/users/index.js

Some controller functions were created and others were updated up from the "logical erase" update

User controllers update

---

api/src/controllers/POST/MercadoPago/paymentServices.js
api/src/routes/GET/movies/search.js
api/src/routes/POST/payment/mercadoPago.js
api/src/routes/index.js

Also minimum fix to search route

FirstPartIntegration:RedirectPayment

---

api/src/controllers/PUT/user/index.js
api/src/routes/PUT/user/admin/handleAdmin.js

ask for HANDLE_ADMIN_PASSWORD value in case u don't have it.

Handle admin route

---

api/src/controllers/GET/users/index.js
api/src/routes/GET/users/allActiveUsers.js
api/src/routes/GET/users/allAvailableUsers.js
api/src/routes/GET/users/allBannedUsers.js
api/src/routes/GET/users/allDeletedUsers.js
api/src/routes/GET/users/allFreeUsers.js
api/src/routes/GET/users/allPremiumUsers.js
api/src/routes/GET/users/allUsers.js
api/src/routes/index.js

/availableUsers: Trae todos los usuarios que tengan banned en false y active en true
/activeUsers: Trae todos los usuarios que tengan active en true
/bannedUsers: Trae todos los usuarios que tengan banned en true
/deletedUsers: Trae todos los usuarios que tengan active en false
/premiumUsers: Trae todos los usuarios que tengan premium en true
/freeUsers: Trae todos los usuarios que tengan premium en false
/allUsers: Trae todos los usuarios

fix: getAllUsers route

---

api/src/controllers/Reviews/reviewsController.js

feature: validate review content, validate mandatory data

Validate post/reviews

---

api/src/controllers/PUT/UpdateReview/index.js

fix: inexisting attribute update. 
Detail: reviews.text doesn't exist.
Correction: text --> content

fix put/reviews

---

api/src/controllers/PUT/list/index.js

controllers updated:
addMovieToList & deleteMovieFromList.
Detail:
changed getListByPk call.

Fix handle movies in list route

---

api/src/models/Actor.js

poner default value false a la propiedad banned de actor

fix model banned defaulValue

---

api/src/controllers/GET/lists/index.js

update: director of each movie and user owner of list added.

update getListAndContent controller

---

api/src/controllers/PUT/list/index.js

fix: the movie id is uuid type so there's no need to format it to integer.

fix add/delete movie from list

---

api/src/db.js

association to handle and save the lists followed by users.
REMEMBER TO REBUILD THE DATABASE. (force=true)..> set as false again once it's done.

feature: Add "followed_lists" association

---

api/src/controllers/POST/list/index.js

create followList,  unfollowList controllers.

feature: add follow/unfollow list controller

---

api/src/routes/POST/list/index.js

Follow example POST/list/:userId?list=:listId&action=follow.
Ufnollow example POST/list/:userId?list=:listId&action=unfollow
I thought the most accurate http method is POST casue we are createing a new row in a table in our db.

feature: POST /list/:userId?list&action
